---

repositories:
  - name: qubership-jaeger
    charts:
      - path: charts/qubership-jaeger/Chart.yaml
        set:
          - proxy.install=true
          - elasticsearch.tls.enabled=true
          - elasticsearch.indexCleaner.install=true
          - elasticsearch.lookback.install=true
          - elasticsearch.rollover.install=true
          - cassandraSchemaJob.enablePreHook=true
          - hotrod.install=true
          - integrationTests.install=true
          - spark.install=true
          - collector.tlsConfig.otelHttp.enabled=true
          - collector.tlsConfig.otelgRPC.enabled=true
          - collector.tlsConfig.jaegerHttp.enabled=true
          - collector.tlsConfig.jaegergRPC.enabled=true
          - collector.tlsConfig.zipkin.enabled=true
          - elasticsearch.client.tls.enabled=true
          - readinessProbe.install=true
          - statusProvisioner.install=true
          - collector.install=true
          - query.install=true
          - jaeger.storage.type=cassandra
  - name: qubership-logging-operator
    charts:
      - path: charts/qubership-logging-operator/Chart.yaml
        set:
          - createClusterAdminEntities=true
          - ipv6=true
          - pprof.install=true
          - graylog.install=true
          - graylog.createIngress=true
          - authProxy.install=true
          - fluentd.install=true
          - fluentbit.install=true
          - fluentbit.aggregator.install=true
          - fluentbit.output.loki.enabled=true
          - fluentbit.output.http.enabled=true
  - name: qubership-monitoring-operator
    charts:
      - path: charts/qubership-monitoring-operator/Chart.yaml
  - name: qubership-env-checker
    charts:
      - path: charts/env-checker/Chart.yaml
        set:
          - OPS_IDP_URL=https://keycloak.k8s.qubership.org
