name: "Docker Build and Publish Composite Action"
description: "Composite action for building and publishing Docker images using Docker Buildx."
inputs:
  ref:
    description: "Branch to create a release from."
    required: false
    default: ""
  custom-image-name:
    description: "Custom name for the Docker image."
    required: false
    default: ""
  context:
    description: "Pipeline context."
    required: false
    default: "git"
  dry-run:
    description: "Run without pushing (dry run)."
    required: false
    default: "false"
  download-artifact:
    description: "Flag to download the artifact."
    required: false
    default: "false"
  component:
    description: "Component configuration in JSON format (an array with a single object)."
    required: false
    default: '[{"name": "default", "file": "./Dockerfile", "context": "."}]'
  platforms:
    description: "Platforms for which the Docker image will be built."
    required: false
    default: "linux/amd64"
  tags:
    description: "Docker image tags. If empty, tags will be generated automatically."
    required: false
    default: ""
  download-artifact-name:
    description: "Name of the artifact to download. Either inputs `artifact-ids` or `name` can be used, but not both. Optional"
    required: false
    default: ""
  download-artifact-ids:
    description: "IDs of the artifacts to download, comma-separated. Either inputs `artifact-ids` or `name` can be used, but not both. Optional"
    required: false
    default: ""
  download-artifact-path:
    description: "Destination path. Supports basic tilde expansion. Optional. Default is $GITHUB_WORKSPACE"
    required: false
    default: ""
  download-artifact-pattern:
    description: "A glob pattern to the artifacts that should be downloaded. Ignored if name is specified. Optional."
    required: false
    default: ""
  download-artifact-merge-multiple:
    description: "When download multiple artifacts unpack them as is or into separate directories. Optional."
    required: false
    default: "false"
  sbom:
    description: "Flag to enable SBoM generation."
    required: false
    default: "false"
  build-args:
    description: "Build arguments for the Docker image, in JSON format."
    required: false
    default: ""
  checkout:
    description: "Flag to enable repository checkout."
    required: false
    default: "true"
  debug:
    description: "Flag to enable debug mode."
    required: false
    default: "false"
  registry:
    description: "Registry name docker.io or ghcr.io or both"
    required: false
    default: "ghcr.io"
  docker-io-login:
    description: "User name to login to docker.io"
    required: false
  docker-io-token:
    description: "Token to login to docker.io"
    required: false
  skip-qemu-buildx:
    description: "DEPRECATED: Use setup-qemu and setup-buildx instead. Skip the setup of both QEMU and Buildx."
    required: false
    default: "false"
  setup-qemu:
    description: "Setup QEMU for multi-platform builds."
    required: false
    default: "true"
  setup-buildx:
    description: "Setup Docker Buildx."
    required: false
    default: "true"
outputs:
  image-name:
    description: "The name of the built Docker image."
    value: "${{ steps.output_result.outputs.image_name }}"
  metadata-json:
    description: "Path to the generated metadata file."
    value: "${{ steps.output_result.outputs.metadata_path }}"
  metadata-filename:
    description: "Name of the generated metadata file."
    value: "${{ steps.output_result.outputs.metadata_filename }}"

runs:
  using: "composite"
  steps:
    - name: Validate inputs.registry
      shell: bash
      env:
        REG: ${{ inputs.registry }}
      run: |
        if [ -z "${REG+x}" ] || [ -z "${REG}" ]; then
          printf "%s\n" "REGISTRY='ghcr.io'" >> "$GITHUB_ENV"
        else
          printf "%s\n" "REGISTRY=$REG" >> "$GITHUB_ENV"
        fi
    - name: Validate docker.io login params
      if: ${{ contains(env.REGISTRY, 'docker.io') && (! inputs.docker-io-login || ! inputs.docker-io-token) && (inputs.dry-run != 'true') }}
      shell: bash
      run: |
        printf "%s\n" "docker.io set as a registry, but docker-io-login and/or docker-io-token not provided."
        exit 1

    - name: Parse Component JSON
      id: parse_component
      shell: bash
      env:
        COMPONENT: ${{ inputs.component }}
      run: |
        # Parse the input JSON object directly
        component="$COMPONENT"
        component_parsed=$(printf "%s\n" "$component" | jq 'if type=="array" then .[0] else . end')
        comp_name=$(printf "%s\n" "$component_parsed" | jq -r '.name')
        comp_file=$(printf "%s\n" "$component_parsed" | jq -r '.file')
        comp_ctx=$(printf "%s\n" "$component_parsed" | jq -r '.context')
        comp_build_args=$(printf "%s\n" "$component_parsed" | jq -r '.arguments // empty')
        printf "%s\n" "name=$comp_name" >> "$GITHUB_OUTPUT"
        printf "%s\n" "file=$comp_file" >> "$GITHUB_OUTPUT"
        printf "%s\n" "ctx=$comp_ctx" >> "$GITHUB_OUTPUT"
        printf "%s\n" "build_args=$comp_build_args" >> "$GITHUB_OUTPUT"

    - name: Prepare Image Name
      shell: bash
      env:
        CUSTOM_IMAGE_NAME: ${{ inputs.custom-image-name }}
        COMPONENT_NAME: ${{ steps.parse_component.outputs.name }}
        DOCKER_IO_LOGIN: ${{ inputs.docker-io-login }}
      run: |
        IFS='/' read -r owner repo <<< "$GITHUB_REPOSITORY"
        if [ -n "$CUSTOM_IMAGE_NAME" ]; then
            CONTAINER_NAME="$CUSTOM_IMAGE_NAME"
        elif [ -n "$COMPONENT_NAME" ] && [ "$COMPONENT_NAME" != "default" ]; then
          CONTAINER_NAME="$COMPONENT_NAME"
        else
          CONTAINER_NAME="$repo"
        fi
        printf "%s\n" "CONTAINER_NAME=$CONTAINER_NAME" >> "$GITHUB_OUTPUT"
        printf "%s\n" "CONTAINER_NAME=$CONTAINER_NAME" >> "$GITHUB_ENV"
        printf "%s\n" "GHCR_OWNER=$(printf "%s\n" "$owner" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
        printf "%s\n" "DOCKER_OWNER=$DOCKER_IO_LOGIN" >> "$GITHUB_ENV"

        printf "%s\n" "CONTAINER_NAME=$CONTAINER_NAME"
        printf "%s\n" "GHCR_OWNER=$GHCR_OWNER"
        printf "%s\n" "DOCKER_OWNER=$DOCKER_OWNER"

    - name: Prepare Image ghcr.io URL
      if: ${{ contains(env.REGISTRY, 'ghcr.io') }}
      shell: bash
      run: |
        printf "%s\n" "GHCR_URL=ghcr.io/${{ env.GHCR_OWNER }}/${{ env.CONTAINER_NAME }}" # safe: handled via env
        printf "%s\n" "GHCR_URL=ghcr.io/${{ env.GHCR_OWNER }}/${{ env.CONTAINER_NAME }}" # safe: handled via env >> "$GITHUB_ENV"

    - name: Prepare Image docker.io URL
      if: ${{ contains(env.REGISTRY, 'docker.io') }}
      shell: bash
      run: |
        printf "%s\n" "DOCKER_URL=${{ env.DOCKER_OWNER }}/${{ env.CONTAINER_NAME }}" # safe: handled via env
        printf "%s\n" "DOCKER_URL=${{ env.DOCKER_OWNER }}/${{ env.CONTAINER_NAME }}" # safe: handled via env >> "$GITHUB_ENV"

    - name: Checkout Repository
      if: ${{ inputs.checkout == 'true' }}
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
      with:
        ref: ${{ inputs.ref }}
        persist-credentials: false

    - name: Display Debug Information
      shell: bash
      env:
        CUSTOM_IMAGE_NAME: ${{ inputs.custom-image-name }}
      run: |
        printf "%s\n" "custom-image-name: ${CUSTOM_IMAGE_NAME:-empty}"
        printf "%s\n" "env CONTAINER_NAME: ${{ env.CONTAINER_NAME }}" # safe: handled via env
        if [ -n "${DOCKER_OWNER}" ]; then
          printf "%s\n" "env DOCKER_OWNER: ${DOCKER_OWNER}"
        fi
        if [ -n "${GHCR_OWNER}" ]; then
          printf "%s\n" "env GHCR_OWNER: ${GHCR_OWNER}"
        fi
        printf "%s\n" "ref: ${{ inputs.ref }}"
        printf "%s\n" "GITHUB_REPOSITORY: ${{ github.repository }}"
        printf "%s\n" "GITHUB_REF: ${{ github.ref }}"
        if [ -n "${DOCKER_URL}" ]; then
          printf "%s\n" "docker.io URL: ${DOCKER_URL}"
        fi
        if [ -n "${GHCR_URL}" ]; then
          printf "%s\n" "ghcr.io URL: ${GHCR_URL}"
        fi

        printf "%s\n" "::group::🐋 MANAGEMENT Dockerfile (alpine)"
        cat ${{ steps.parse_component.outputs.file }}
        printf "%s\n" "::endgroup::"

    - name: Download Artifact
      if: ${{ inputs.download-artifact == 'true' }}
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 #v6.0.0
      with:
        name: ${{ inputs.download-artifact-name }}
        path: ${{ inputs.download-artifact-path != '' && inputs.download-artifact-path || '.' }}
        merge-multiple: ${{ inputs.download-artifact-merge-multiple == 'true' }}

    - name: Debug ls
      if: ${{ inputs.debug == 'true' }}
      shell: bash
      env:
        DL_PATH: ${{ inputs.download-artifact-path }}
        CONTEXT_DIR: ${{ steps.parse_component.outputs.ctx }}
      run: |
        printf "%s\n" "🔍 Current directory:"
        pwd
        printf "%s\n" "📂 Full workspace tree:"
        ls -R -la ${{ github.workspace }}

    - name: Set up QEMU
      if: ${{ inputs.setup-qemu == 'true' && inputs.skip-qemu-buildx != 'true' }}
      uses: docker/setup-qemu-action@a802a07b7743d8b2bb4b8e8a7c293c3b31e1e5f8 # v3

    - name: Set up Docker Buildx
      if: ${{ inputs.setup-buildx == 'true' && inputs.skip-qemu-buildx != 'true' }}
      uses: docker/setup-buildx-action@c3d2b6c9ff9e7b4c9d6a2a5ea0d3e0de5438a993 # v3

    - name: Log in to GitHub Container Registry
      if: ${{ contains(env.REGISTRY, 'ghcr.io') }}
      uses: docker/login-action@9b1f6e4b8b972f5e3b5c1891b52c9f6635a7c0e3 # v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ env.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      if: ${{ contains(env.REGISTRY, 'docker.io') }}
      uses: docker/login-action@9b1f6e4b8b972f5e3b5c1891b52c9f6635a7c0e3 # v3
      with:
        username: ${{ inputs.docker-io-login }}
        password: ${{ inputs.docker-io-token }}

    - name: Extract Docker Metadata
      if: ${{ inputs.tags == '' }}
      id: meta
      uses: docker/metadata-action@9a4d3d2a8f97b1a73b8f8c8b5f4d276bfde6e82c # v5
      with:
        context: ${{ inputs.context }}
        images: |
          ${{ env.GHCR_URL }}
          ${{ env.DOCKER_URL }}
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Create Image Refs (docker ghcr.io/owner/name:tag)
      if: ${{ inputs.tags != '' }}
      id: create-image-refs
      shell: bash
      env:
        TAGS_INPUT: ${{ inputs.tags }}
      run: |
        printf "%s\n" "Create Image Refs (docker ghcr.io/owner/name:tag)"
        TAGS_INPUT="${{ inputs.tags }}"

        IFS=',' read -ra TAGS <<< "$TAGS_INPUT"

        IMAGE_REFS=""
        if [ -n "${GHCR_URL}" ]; then
          for TAG in "${TAGS[@]}"; do
            TAG=$(printf "%s\n" "$TAG" | xargs)
            IMAGE_REFS="$IMAGE_REFS,$GHCR_URL:$TAG"
          done
        fi
        if [ -n "${DOCKER_URL}" ]; then
          for TAG in "${TAGS[@]}"; do
            TAG=$(printf "%s\n" "$TAG" | xargs)
            IMAGE_REFS="$IMAGE_REFS,$DOCKER_URL:$TAG"
          done
        fi
        IMAGE_REFS="${IMAGE_REFS#,}"
        IMAGE_REFS=$(printf "%s\n" "$IMAGE_REFS" | tr '[:upper:]' '[:lower:]')

        printf "%s\n" "Image refs: $IMAGE_REFS"
        printf "%s\n" "IMAGE_REFS=$(printf "%s\n" "$IMAGE_REFS" | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

    - name: Build and Push Docker Image
      uses: docker/build-push-action@7b08a6e8a967f9cfd95bfaf062c4b3cbdc5a9d7e # v6
      id: dockerbuild
      with:
        provenance: false
        sbom: ${{ inputs.sbom == 'true' && 'true' || 'false' }}
        context: ${{ steps.parse_component.outputs.ctx }}
        file: ${{ steps.parse_component.outputs.file }}
        push: ${{ inputs.dry-run == 'true' && 'false' || 'true' }}
        tags: ${{ inputs.tags != '' && env.IMAGE_REFS || steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ steps.parse_component.outputs.build_args != '' && steps.parse_component.outputs.build_args || inputs.build-args }}

    - name: Output result
      if: ${{ ! (inputs.dry-run == 'true') }}
      id: output_result
      shell: bash
      run: |
        set -euo pipefail

        IMAGE_NAME_FULL="${{ fromJson(steps.dockerbuild.outputs.metadata)['image.name'] }}"
        IMAGE_NAME_FULL="${IMAGE_NAME_FULL%%,*}"

        if [ -z "$IMAGE_NAME_FULL" ]; then
          printf "%s\n" "ERROR: IMAGE_NAME_FULL is empty. Check dockerbuild.outputs.metadata / image.name"
          exit 1
        fi

        printf "%s\n" "IMAGE_NAME_FULL=$IMAGE_NAME_FULL"

        IMAGE_NAME="${IMAGE_NAME_FULL%%:*}"
        TAG="${IMAGE_NAME_FULL##*:}"

        if [ -z "$IMAGE_NAME" ] || [ -z "$TAG" ]; then
          printf "%s\n" "ERROR: IMAGE_NAME or TAG is empty. Got: IMAGE_NAME='$IMAGE_NAME', TAG='$TAG'"
          exit 1
        fi

        DIGEST="${{ steps.dockerbuild.outputs.digest }}"
        if [ -z "$DIGEST" ]; then
          printf "%s\n" "ERROR: DIGEST is empty. Check dockerbuild.outputs.digest"
          exit 1
        fi

        ALG="${DIGEST%%:*}"
        DIGEST_NO_PREFIX="${DIGEST##*:}"
        DIGEST_SHORT="${DIGEST_NO_PREFIX:0:12}"

        GROUP="${{ inputs.app-manifest-group || '' }}"

        VERSION="$TAG"

        BASENAME="$(basename "$IMAGE_NAME")"
        FILENAME="${BASENAME}-${TAG}-${DIGEST_SHORT}.json"

        printf "%s\n" ">>> IMAGE_NAME        = $IMAGE_NAME"
        printf "%s\n" ">>> TAG               = $TAG"
        printf "%s\n" ">>> DIGEST            = $DIGEST"
        printf "%s\n" ">>> DIGEST_SHORT(12)  = $DIGEST_SHORT"
        printf "%s\n" ">>> FILENAME          = $FILENAME"

        REFERENCE="${IMAGE_NAME}:${VERSION}"

        cat <<EOF > "$FILENAME"
        {
          "type": "container",
          "mime-type": "application/vnd.docker.image",
          "name": "${CONTAINER_NAME}",
          "group": "${GROUP}",
          "version": "${VERSION}",
          "hashes": [
            {
              "alg": "${ALG}",
              "content": "${DIGEST_NO_PREFIX}"
            }
          ],
          "reference": "${REFERENCE}"
        }
        EOF

        printf "%s\n" "image_name=$IMAGE_NAME_FULL" >> "$GITHUB_OUTPUT"
        printf "%s\n" "metadata_path=$PWD/$FILENAME" >> "$GITHUB_OUTPUT"
        printf "%s\n" "metadata_filename=$FILENAME" >> "$GITHUB_OUTPUT"

    - name: "Upload metadata file"
      if: ${{ ! (inputs.dry-run == 'true') }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.output_result.outputs.metadata_filename }}
        path: ${{ steps.output_result.outputs.metadata_path }}
