name: 'Upload Release Assets'
description: 'Uploads all files from a folder to a GitHub release'
inputs:
  path:
    description: 'Path to folder containing files'
    required: true
  upload_url:
    description: 'Upload URL of the release (from create-release step)'
    required: true
runs:
  using: 'node16'
  main: 'index.js'