name: "Change Helm Chart.yaml"
description: "Update the version (and optionally appVersion) field in a Helm Chart.yaml using yq."

inputs:
  new-chart-version:
    description: "The version of the Helm chart."
    required: true
  chart-app-version:
    description: "The version of the application."
    required: false
  chart-yaml-path:
    description: "The path to the Chart.yaml file."
    required: true

runs:
  using: "composite"
  steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
        with:
          persist-credentials: false

      - name: Install yq
        shell: bash
        run: |
              wget -q https://github.com/mikefarah/yq/releases/download/v4.34.1/yq_linux_amd64 -O yq
              chmod +x yq
              sudo mv yq /usr/local/bin/yq

      - name: Eval Chart.yaml
        shell: bash
        run: |
                current_version=$(yq '.version' ${{ inputs.chart-yaml-path }})
                echo "::warning:: 💡 Change: $current_version" to  ${{ inputs.new-chart-version }}
                yq eval '.version = "${{ inputs.new-chart-version }}"' -i  ${{ inputs.chart-yaml-path }}
                echo "::notice::✅ Successfully updated version!"

