---
name: Discover GHCR Packages for Repository
description: List all GHCR container packages associated with a specific repository.
author: Nookyo
inputs:
  owner:
    description: "The owner of the repository. Defaults to the current repository owner."
    required: false
  repository:
    description: "The name of the repository. Defaults to the current repository name."
    required: false
  fetch-tags:
    description: "Fetch default/latest tag for each package."
    required: false
    default: "false"
outputs:
  packages:
    value: ${{ steps.discover.outputs.packages }}
    description: "A JSON array of GitHub Container Registry packages for the specified repository."
  has-packages:
    value: ${{ steps.discover.outputs.has-packages }}
    description: "True if repo has at least one GHCR package."

runs:
  using: "composite"
  steps:
    - name: Show raw GHCR response
      shell: bash
      id: discover
      env:
        GH_TOKEN: ${{ env.GH_TOKEN || github.token }}
        OWNER: ${{ inputs.owner || github.repository_owner }}
        REPO: ${{ inputs.repository || github.event.repository.name }}
        FETCH_TAGS: ${{ inputs.fetch-tags }}
      run: |
        set -euo pipefail
        per_page=100
        page=1
        filtered_packages='[]'
        all_packages='[]'

        echo "Fetching GHCR packages for owner: $OWNER, repo: $REPO"

        while :; do
          api_url="https://api.github.com/orgs/${OWNER}/packages?package_type=container&per_page=${per_page}&page=${page}"
          echo "Request: $api_url"

          response=$(curl -sS \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "$api_url")

          if ! echo "$response" | jq -e 'type == "array"' >/dev/null 2>&1; then
            echo "Non-array response from GitHub API (maybe error):"
            echo "$response"
            break
          fi

          count=$(echo "$response" | jq 'length')
          echo "Page $page: $count packages"

          if [ "$count" -eq 0 ]; then
            echo "No more pages."
            break
          fi

          all_packages=$(printf '%s\n%s\n' "$all_packages" "$response" | jq -c -s 'add')

          page_filtered=$(echo "$response" | jq -c --arg owner "$OWNER" --arg repo "$REPO" '
            [.[]
            | select(.repository.full_name == "\($owner)/\($repo)")
            | {
                name: .name,
                repository: (.repository.name // null),
                full_name: (.repository.full_name // null),
                path: "ghcr.io/\($owner)/\(.name)"
              }
            ]
          ')

          echo "Page $page filtered packages:"
          echo "$page_filtered" | jq '.'

          filtered_packages=$(printf '%s\n%s\n' "$filtered_packages" "$page_filtered" | jq -c -s 'add')

          page=$((page + 1))
        done

        echo "Final filtered packages for repo $REPO:"
        echo "$filtered_packages" | jq '.'

        # Fetch default tags if requested
        if [ "$FETCH_TAGS" = "true" ]; then
          echo "Fetching default tags for packages..."
          packages_with_tags='[]'
          
          package_count=$(echo "$filtered_packages" | jq 'length')
          
          for i in $(seq 0 $((package_count - 1))); do
            pkg_name=$(echo "$filtered_packages" | jq -r ".[$i].name")
            
            echo "Fetching tags for package: $pkg_name"
            
            versions_url="https://api.github.com/orgs/${OWNER}/packages/container/${pkg_name}/versions?per_page=100"
            versions_response=$(curl -sS \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "$versions_url")
            
            # Find the latest tagged version
            default_tag=$(echo "$versions_response" | jq -r '[.[] | select(.metadata.container.tags | length > 0)] | sort_by(.created_at) | reverse | .[0].metadata.container.tags[0] // "unknown"')
            
            # Add default_tag to the package object
            pkg_with_tag=$(echo "$filtered_packages" | jq ".[$i] + {default_tag: \"$default_tag\"}")
            packages_with_tags=$(echo "$packages_with_tags" | jq ". + [$pkg_with_tag]")
          done
          
          filtered_packages="$packages_with_tags"
          echo "Packages with default tags:"
          echo "$filtered_packages" | jq '.'
        fi

        echo "Total packages collected (all pages):"
        echo "$all_packages" | jq 'length'

        echo "$all_packages" > ghcr_all_packages.json
        echo "$filtered_packages" > ghcr_filtered_packages.json

        has_packages=$(echo "$filtered_packages" | jq 'length > 0')

        echo "packages=$filtered_packages" >> "$GITHUB_OUTPUT"
        echo "has-packages=$has_packages" >> "$GITHUB_OUTPUT"
