name: "[REUSABLE] Python build"

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      poetry_version_options:
        required: false
        type: string
        default: 'patch'
      python-version:
        required: false
        type: string
        default: '3.11'
      poetry_build_params:
        required: false
        type: string
      pytest_run:
        required: true
        type: boolean
      pytest_params:
        required: false
        type: string
      gh_app_id:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: ''
    secrets:
      PYPI_API_TOKEN:
        required: true
      GH_APP_KEY:
        required: true

jobs:
  build-publish:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment || '' }}
    steps:
      - name: Debug variables
        env:
          INPUT_VERSION: ${{ inputs.version }}
          INPUT_POETRY_VERSION_OPTIONS: ${{ inputs.poetry_version_options }}
          INPUT_PYTHON_VERSION: ${{ inputs.python-version }}
          INPUT_POETRY_BUILD_PARAMS: ${{ inputs.poetry_build_params }}
          INPUT_PYTEST_RUN: ${{ inputs.pytest_run }}
          INPUT_PYTEST_PARAMS: ${{ inputs.pytest_params }}
        run: |
          echo "version = $INPUT_VERSION"
          echo "poetry_version_options = $INPUT_POETRY_VERSION_OPTIONS"
          echo "python-version = $INPUT_PYTHON_VERSION"
          echo "poetry_build_params = $INPUT_POETRY_BUILD_PARAMS"
          echo "pytest_run = $INPUT_PYTEST_RUN"
          echo "pytest_params = $INPUT_PYTEST_PARAMS"

          echo "Environment:"
          env

      - name: "Prepare app token"
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          app-id: ${{ inputs.gh_app_id }}
          private-key: ${{ secrets.GH_APP_KEY }}
          permission-contents: write

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install dependencies 3.8
        if: ${{ inputs.python-version == '3.8' }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        if: ${{ inputs.python-version != '3.8' }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user pipx
          pipx install poetry

      - name: Remove dist
        run: rm -rf dist/

      - name: AutoPatch version
        if: ${{ inputs.poetry_version_options != '' && inputs.version == '' }}
        env:
          POETRY_VERSION_OPTIONS: ${{ inputs.poetry_version_options }}
        run: poetry version "$POETRY_VERSION_OPTIONS"

      - name: Set specific version
        if: ${{ inputs.version != '' }}
        env:
          INPUT_VERSION: ${{ inputs.version }}
        run: poetry version "$INPUT_VERSION"

      - name: Build package
        env:
          POETRY_BUILD_PARAMS: ${{ inputs.poetry_build_params }}
        run: poetry build $POETRY_BUILD_PARAMS

      - name: Validate build
        run: |
          ls -l dist/
          echo "Build validation complete."

      - name: Run tests
        if: ${{ inputs.pytest_run == true }}
        env:
          PYTEST_PARAMS: ${{ inputs.pytest_params }}
        run: |
          poetry install
          poetry run pytest $PYTEST_PARAMS

      - name: Publish to PyPi
        # zizmor: ignore[use-trusted-publishing]
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --no-interaction -p test
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}

      - name: Update Source on GitHub
        env:
          INPUT_VERSION: ${{ inputs.version }}
        run: |
          git config --global user.email "qubership-actions[bot]@users.noreply.github.com"
          git config --global user.name "qubership-actions[bot]"
          git add .
          git commit -m "Update version to $INPUT_VERSION for release"
          git push -u origin main
