name: Security Scan
on:
  workflow_dispatch:
    inputs:
      target:
        description: "Scan part"
        required: true
        default: "docker"
        type: choice
        options:
          - docker
          - source
      image:
        description: "Docker image (for 'docker' target). By default ghcr.io/<owner>/<repo>:latest"
        required: false
        default: ""
      only-high-critical:
        description: "Scan only HIGH + CRITICAL"
        required: false
        default: true
        type: boolean
      trivy-scan:
        description: "Run Trivy scan"
        required: false
        default: true
        type: boolean
      grype-scan:
        description: "Run Grype scan"
        required: false
        default: true
        type: boolean
      continue-on-error:
        description: "Continue on error"
        required: false
        default: true
        type: boolean
      only-fixed:
        description: "Show only fixable vulnerabilities"
        required: false
        default: true
        type: boolean

  schedule:
    - cron: "0 3 * * 0"

permissions:
  contents: read
  security-events: write
  actions: read
  packages: read

jobs:
  security-scan:
    name: "Run Security Scan"
    uses: nookyo/qubership-workflow-hub/.github/workflows/re-scam.yml@main
    with:
      target: ${{ github.event.inputs.target || 'source' }}
      image: ${{ github.event.inputs.image || format('ghcr.io/{0}:latest', github.repository) }}
      only-high-critical: ${{ github.event.inputs.only-high-critical || true }}
      trivy-scan: ${{ github.event.inputs.trivy-scan || true }}
      grype-scan: ${{ github.event.inputs.grype-scan || true }}
      only-fixed: ${{ github.event.inputs.only-fixed || true }}
      continue-on-error: ${{ github.event.inputs.continue-on-error || true }}
