name: Try to test NEw PR Assiner
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug
        run:  ls -la

        
      - name: Test PR Assigner
        uses: nookyo/qubership-workflow-hub/actions/pr-assigner@main
